<?php


namespace backend\controllers;


use common\exceptions\ApiException;
use Yii;
use yii\base\DynamicModel;

class UserController extends BaseController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->success('success');
    }

    public function actionError()
    {
        return $this->error(10001, '错误信息');
    }

    public function actionLogin()
    {
        $data = Yii::$app->request->post();

        $validate = DynamicModel::validateData($data, [
            [['username', 'password'], 'required'],
            ['username', 'string', 'max' => 10],
            ['password', 'string', 'max' => 10],
        ]);

        if ($validate->hasErrors()) {
            throw new ApiException(ApiException::PARAM_ERROR);
        }

        if ($validate->username != 'demo' || $validate->password != 'demo') {
            throw new ApiException(ApiException::PARAM_ERROR, '账号信息不对');
        }

        return $this->success('success', ['token' => '57f20f883e']);
    }

    public function actionCountry()
    {
        $country = [
            [
                'code' => 'AU',
                'name' => 'Australia',
                'population' => '18886000',
            ],
            [
                'code' => 'BR',
                'name' => 'Brazil',
                'population' => '170115000',
            ],
            [
                'code' => 'CA',
                'name' => 'Canada',
                'population' => '1147000',
            ],
            [
                'code' => 'CN',
                'name' => 'China',
                'population' => '1277558000',
            ],
            [
                'code' => 'DE',
                'name' => 'Germany',
                'population' => '82164700',
            ],
            [
                'code' => 'FR',
                'name' => 'France',
                'population' => '59225700',
            ],
            [
                'code' => 'GB',
                'name' => 'United Kingdom',
                'population' => '59623400',
            ],
            [
                'code' => 'IN',
                'name' => 'India',
                'population' => '1013662000',
            ],
            [
                'code' => 'RU',
                'name' => 'Russia',
                'population' => '146934000',
            ],
            [
                'code' => 'US',
                'name' => 'United States',
                'population' => '278357000',
            ],
        ];

        return $this->success('success', compact('country'));
    }
}