<?php


namespace backend\models;


class AdminRoleModel extends BaseModel
{
    public static function tableName()
    {
        return 't_admin_role'; // TODO: Change the autogenerated stub
    }


}