<?php


namespace backend\models;


class PermissionModel extends BaseModel
{
    public static function tableName()
    {
        return 't_permission'; // TODO: Change the autogenerated stub
    }

}