<?php


namespace backend\models;


class PermissionModel extends BaseModel
{
    public static function tableName()
    {
        return 't_permission'; // TODO: Change the autogenerated stub
    }

    public function getRoles()
    {
        return $this->hasMany(RoleModel::className(), ['id' => 'role_id'])
            ->viaTable('t_role_permission', ['permission_id' => 'id']);
    }
}