<?php


namespace backend\models;


class RolePermissionModel extends BaseModel
{
    public static function tableName()
    {
        return 't_role_permission'; // TODO: Change the autogenerated stub
    }


}