<?php


namespace backend\models;


class RoleModel extends BaseModel
{
    public static function tableName()
    {
        return 't_role'; // TODO: Change the autogenerated stub
    }

    public function getPermissions()
    {
        return $this->hasMany(PermissionModel::className(), ['id' => 'permission_id'])
            ->viaTable('t_role_permission', ['role_id' => 'id']);
    }
}